// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED_FOR_SECURITY',
    appId: '1:998645800995:web:21de541336e480553e1196',
    messagingSenderId: '998645800995',
    projectId: 'hustlr-8e903',
    authDomain: 'hustlr-8e903.firebaseapp.com',
    storageBucket: 'hustlr-8e903.firebasestorage.app',
    measurementId: 'G-ZF5Y17FEGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED_FOR_SECURITY',
    appId: '1:998645800995:android:4c528848ef98bc753e1196',
    messagingSenderId: '998645800995',
    projectId: 'hustlr-8e903',
    storageBucket: 'hustlr-8e903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED_FOR_SECURITY',
    appId: '1:998645800995:ios:187faf14415d34863e1196',
    messagingSenderId: '998645800995',
    projectId: 'hustlr-8e903',
    storageBucket: 'hustlr-8e903.firebasestorage.app',
    iosBundleId: 'com.shieldgig.shieldgig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED_FOR_SECURITY',
    appId: '1:998645800995:ios:187faf14415d34863e1196',
    messagingSenderId: '998645800995',
    projectId: 'hustlr-8e903',
    storageBucket: 'hustlr-8e903.firebasestorage.app',
    iosBundleId: 'com.shieldgig.shieldgig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED_FOR_SECURITY',
    appId: '1:998645800995:web:68a0dc0f5123cbad3e1196',
    messagingSenderId: '998645800995',
    projectId: 'hustlr-8e903',
    authDomain: 'hustlr-8e903.firebaseapp.com',
    storageBucket: 'hustlr-8e903.firebasestorage.app',
    measurementId: 'G-7X2JQM3145',
  );
}
